[package]
name                      = "get_version"
description               = "Implementation of an IPFS HTTP API client"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]
edition                   = "2018"
documentation             = "https://docs.rs/ipfs-api"
repository                = "https://github.com/ferristseng/rust-ipfs-api"
keywords                  = ["ipfs"]
categories                = ["filesystem", "web-programming"]
version                   = "0.10.0"
license                   = "MIT OR Apache-2.0"

[[bin]]
name = "get_version"
path = "get_version.rs"

[features]
default                   = ["with-hyper-tls", "with-builder"]
with-hyper-tls            = ["with-hyper", "hyper-tls"]
with-hyper-rustls         = ["with-hyper", "hyper-rustls"]
with-hyper                = ["hyper", "hyper-multipart-rfc7578", "failure"]
with-actix                = ["actix-http", "actix-multipart-rfc7578", "awc", "derive_more"]
with-builder              = ["typed-builder"]
# Old features, kept for compatibility
actix                     = ["with-actix"]
builder                   = ["with-builder"]

[dependencies]
ipfs-api = "0.7.1"
actix-http                = { version = "1.0", optional = true }
actix-multipart-rfc7578   = { version = "0.3.0-rc", optional = true }
awc                       = { version = "1.0", optional = true }
bytes                     = "0.5"
derive_more               = { version = "0.99", optional = true }
failure                   = { version = "0.1.6", optional = true }
futures                   = "0.3.12"
http                      = "0.2"
hyper                     = { version = "0.13", optional = true }
hyper-tls                 = { version = "0.4", optional = true }
hyper-rustls              = { version = "0.20", optional = true }
hyper-multipart-rfc7578   = { version = "0.4.0-rc", optional = true }
serde                     = { version = "1.0", features = ["derive"] }
serde_json                = "1.0"
serde_urlencoded          = "0.6"
tokio                     = "0.2"
tokio-util                = { version = "0.3", features = ["codec"] }
walkdir                   = "2.3"
dirs                      = "3.0"
parity-multiaddr          = "0.9"
typed-builder             = { version = "0.6", optional = true }

[dev-dependencies]
actix-http                = "1.0"
actix-multipart-rfc7578   = "0.3.0-rc"
actix-rt                  = "1.0"
awc                       = "1.0"
hyper                     = "0.13"
hyper-tls                 = "0.4"
tar                       = "0.4"
tokio                     = { version = "0.2", features = ["rt-threaded", "macros", "time"] }
