[package]
name = "graph-server-index-node"
version = "0.21.1"
edition = "2018"

[dependencies]
futures = "0.3.12"
graph = { path = "../../graph" }
graph-graphql = { path = "../../graphql" }
graphql-parser = "0.3"
http = "0.2.3"
hyper = "0.13.9"
serde = "1.0.123"
